services:
  server:
    container_name: her-server
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - server/.env
    image: ghcr.io/matuszelenak/her-server:latest
    ports:
      - "8069:8000"

  ui:
    container_name: her-ui
    restart: unless-stopped
    image: ghcr.io/matuszelenak/her-ui:latest
    depends_on:
      - server
    ports:
      - "5069:80"

  database:
    container_name: her-database
    restart: unless-stopped
    image: postgres:14.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
