services:
  nginx:
    container_name: ai-girlfriend-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server
      - ui

  database:
    container_name: ai-girlfriend-database
    image: postgres:14.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  server:
    container_name: ai-girlfriend-server
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: uvicorn server:app --host 0.0.0.0 --port 8000 --reload --timeout-graceful-shutdown 0
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: server/requirements.txt
        - action: sync
          path: server
          target: /app
    volumes:
      - ./tts_output:/tts_output

  assistant:
    container_name: ai-girlfriend-assistant
    build:
      context: ./assistant
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./assistant/.env
    develop:
      watch:
        - action: rebuild
          path: assistant/requirements.txt
        - action: sync
          path: assistant
          target: /app

  ui:
    container_name: ai-girlfriend-ui
    build:
      context: ui
      dockerfile: dev.Dockerfile
    depends_on:
      - server
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: rebuild
          path: ./ui/package.json
        - action: sync
          path: ./ui
          target: /app
          ignore:
            - node_modules/

  ui-svelte:
    container_name: ai-girlfriend-ui-svelte
    build:
      context: svelte-ui
      dockerfile: dev.Dockerfile
    depends_on:
      - server
    ports:
      - "5001:5000"
    develop:
      watch:
        - action: rebuild
          path: ./ui/package.json
        - action: sync
          path: ./svelte-ui
          target: /app
          ignore:
            - node_modules/


volumes:
  postgres-data:
