services:
  server:
    container_name: ai-girlfriend-server
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  ui:
    container_name: ai-girlfriend-ui
    build:
      context: ui
      dockerfile: dev.Dockerfile
    depends_on:
      - server
    ports:
      - "5000:5000"
    volumes:
      - ./ui:/app